image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
  - prepare
  - test
  - build
  - pypi
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /Add changelog for version .*/
      when: never
    - when: always

prepare:
  stage: prepare
  tags:
    - docker
  image: "python:latest"
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" -X POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG"'

test:
  stage: test
  tags:
    - docker
  image: "python:$VERSION"
  script:
    - python --version ; pip --version  # For debugging
    - pip install pytest tox click
    - tox -e py${VERSION}
  parallel:
    matrix:
      - VERSION: ['3.9', '3.11']
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
    paths:
      - report.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

build:
  stage: build
  tags:
    - docker
  image: "python:latest"
  script:
    - pip install build
    - python3 -m build
  artifacts:
    paths:
      - dist/

pypi_test:
  stage: pypi
  tags:
    - docker
  image: "python:latest"
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  variables:
    TWINE_USERNAME: $PYPI_TEST_USERNAME
    TWINE_PASSWORD: $PYPI_TEST_PASSWORD
  script:
    - pip install twine
    - python3 -m twine upload --repository testpypi --skip-existing dist/*

pypi_prod:
  stage: pypi
  tags:
    - docker
  image: "python:latest"
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    TWINE_USERNAME: $PYPI_PROD_USERNAME
    TWINE_PASSWORD: $PYPI_PROD_PASSWORD
  script:
    - pip install twine
    - python3 -m twine upload dist/*

release_job:
  stage: release
  tags:
    - docker
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
