image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://docs.gitlab.com/ci/caching/#inherit-global-configuration-but-override-specific-settings-per-job
default:
  cache: &global_cache
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/pip
    policy: pull-push

stages:
  - build_cache
  - prepare
  - test
  - build
  - pypi
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /Add changelog for version .*/
      when: never
    - when: always

build-cache:
  stage: build_cache
  tags:
    - docker
  image: python:latest
  script:
    - python --version
    - pip --version  # For debugging
    - pip install -U pip
    - pip install hatch

prepare:
  stage: prepare
  tags:
    - docker
  image: "python:latest"
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" -X POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG"'

test:
  stage: test
  tags:
    - docker
  image: "python:$VERSION"
  script:
    - python --version ; pip --version  # For debugging
    - pip install hatch
    - hatch test -v --cover
  parallel:
    matrix:
      - VERSION: ['3.10', '3.11', '3.12']
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

build:
  stage: build
  tags:
    - docker
  image: "python:latest"
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - pip install hatch
    - hatch build
  artifacts:
    paths:
      - dist/

pypi_test:
  stage: pypi
  tags:
    - docker
  image: "python:latest"
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  variables:
    HATCH_INDEX_REPO: test
    HATCH_INDEX_USER: $PYPI_TEST_USERNAME
    HATCH_INDEX_AUTH: $PYPI_TEST_PASSWORD
  script:
    - pip install hatch
    - hatch publish

pypi_prod:
  stage: pypi
  tags:
    - docker
  image: "python:latest"
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    HATCH_INDEX_USER: $PYPI_PROD_USERNAME
    HATCH_INDEX_AUTH: $PYPI_PROD_PASSWORD
  script:
    - pip install hatch
    - hatch publish

release_job:
  stage: release
  tags:
    - docker
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
